sudo: required
services:
  - docker

before_install:
  - docker build -t petrph/react-test -f ./client/Dockerfile.dev ./client

#run tests
script:
  - docker run -e CI=true petrph/react-test npm test

#build images and push to docker hub
after_success:
  - docker build -t petrph/multi-client ./client
  - docker build -t petrph/multi-nginx ./nginx
  - docker build -t petrph/multi-server ./server
  - docker build -t petrph/multi-worker ./worker
  # login to docker with vars from travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker
  - docker push petrph/multi-client
  - docker push petrph/multi-nginx
  - docker push petrph/multi-server
  - docker push petrph/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-645677211427
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY